import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import useDrupalJSONAPI from "../hooks/useDrupalJSONAPI";

export default function articles({ articles, photos }) {
  return (
    <div>
      <Head>
        <title>Create Next App + Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="prose mx-auto py-16 flex flex-col items-center justify-center">
        <Link href="/">
          <a>Home</a>
        </Link>
        <div className="divide-y-4 divide-gray-200 space-y-4 py-12">
          <h1>Articles</h1>
          {articles?.map((article, index) => {
            return (
              <article key={article.id} className="prose py-4">
                <h3>{article.attributes.title}</h3>
                <Image
                  src={
                    "https://dev-drupal-api-testing.pantheonsite.io" +
                    photos[index].attributes.uri.url
                  }
                  alt="some image" //TODO : figure out how to get alt text???
                  width={1600}
                  height={900}
                />
                <p>{article.attributes.body.value}</p>
              </article>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  let articlesData = await useDrupalJSONAPI({
    baseURL: "https://dev-drupal-api-testing.pantheonsite.io/",
    collection: "article",
    include: ["field_image"],
  });
  const { data: articles, included: photos } = articlesData;

  return {
    props: { articles, photos },
  };
}
