import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App + Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="prose mx-auto py-16 flex flex-col items-center justify-center">
        <h1>Welcome to Next.js + Tailwind+ Decoupled Drupal !</h1>
        <Link href="/articles">
          <a>View Articles</a>
        </Link>
        <Link href="/people">
          <a>View People</a>
        </Link>
      </main>
    </div>
  );
}
