import Head from "next/head";
import Link from "next/link";
import { useDrupalJSONAPI } from "react-drupal-json-api";

export default function text({ articles }) {
  return (
    <div>
      <Head>
        <title>Create Next App + Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="prose mx-auto py-16 flex flex-col items-center justify-center">
        <Link href="/">
          <a>Home</a>
        </Link>
        <div className="divide-y-4 divide-gray-200 space-y-4 py-12">
          <h1>Just Text</h1>
          {articles?.map((article, index) => {
            return (
              <article key={article.id} className="prose py-4">
                <h3>{article.attributes.title}</h3>
                <div
                  id="danger"
                  dangerouslySetInnerHTML={{
                    __html: article.attributes.body?.processed,
                  }}
                />
              </article>
            );
          })}
        </div>
      </main>
    </div>
  );
}

export async function getStaticProps() {
  let articlesData = await useDrupalJSONAPI({
    baseURL: "https://dev-drupal-api-testing.pantheonsite.io/",
    collection: "article",
    include: ["field_image"],
    sort: "created",
  });
  const { data: articles } = articlesData;

  return {
    props: { articles },
  };
}
